version: "3.3"
services:
    flask:
        image: jnp-flask
        ports:
            - 8012:80
        volumes:
            - ./src:/src
        command: >
            bash -c "./wait-for-it.sh rating_rabbitmq:5672 -- python rates.py"
        networks:
            - rates-1
            - jnp-internal-1

    redis:
        image: redis
        networks:
            - rates-1

networks:
    jnp-internal-1:
        external: true
    rates-1:
