version: "3.3"
services:
    flask:
        image: jnp-flask
        ports:
            - 8021:80
        volumes:
            - ./src:/src
        command: >
            bash -c "python session.py"
        networks:
            - session-1
            - jnp-internal-1

    redis:
        image: redis
        networks:
            - session-1

networks:
    jnp-internal-1:
        external: true
    session-1:
